Display toast on operation success
zer0tonin/Mikochi pull request #19
Opened 2024-10-01 20:33 UTC by AdithyaPadmashali

This PR addresses issue #17 

Approach:
Make a re-usable global app context using Context API and use that to decide the message to display on the toast. This way, the common toast can be used to display all types of messages based on which operation was performed.

Also the global app context could be useful for later development.

Example outcome:

![image](https://github.com/user-attachments/assets/6c0c7eea-f4a9-4717-b593-9a5de15ad426)

2024-10-01 21:36 UTC, zer0tonin requested changes
Thank you for your pull request. The main issue is that it currently doesn't really work and causes the following error when launching the project:
```
Error:   Failed to scan for dependencies from entries:
/app/index.html

✘ [ERROR] The JSX syntax extension is not currently enabled
states/provider.js:11:8:
    <AppStateContext.Provider value={{ state, dispatch }}>
```

Make sure to test your code before committing. To launch Mikochi, you simply need to have docker installed, then just run `make dev` (or `docker-compose up dev -d`).

2024-10-01 21:36 UTC, zer0tonin commented on frontend/states/provider.js
> +import React from 'react'
Mikochi isn't a React project, we use preact which you can import like this:
```js
import { h } from "preact";
import { useReducer } from "preact/hooks";
```

2024-10-01 21:36 UTC, zer0tonin commented on frontend/states/reducer.js
> +export const reducer = (state, action) => {
Using reducers seems overkill to me. The toast is only going to display a singe string that doesn't depend on previous states. Using a `useState`/`useMemo` like for the `AuthContext` would remove quite a bit of boilerplate.

2024-10-02 20:40 UTC, AdithyaPadmashali commented
I understand. Opened another PR with a simpler implementation #20

2024-10-02 20:40 UTC, closed without merging